recipes.remove(<xnet:antenna>);
recipes.addShaped(<xnet:antenna>, [[<techreborn:plates:32>, <techreborn:ingot:17>, <techreborn:plates:32>],[<techreborn:plates:32>, <techreborn:ingot:17>, <techreborn:plates:32>], [null, <techreborn:ingot:17>, null]]);
recipes.remove(<xnet:antenna_base>);
recipes.addShaped(<xnet:antenna_base>, [[null, <techreborn:ingot:17>, null],[null, <techreborn:ingot:17>, null], [<techreborn:ingot:17>, <techreborn:storage2>, <techreborn:ingot:17>]]);
recipes.remove(<xnet:wireless_router>);
recipes.addShaped(<xnet:wireless_router>, [[<immersiveengineering:wooden_device0:3>, <techreborn:plates:16>, <immersiveengineering:wooden_device0:7>],[<minecraft:end_rod>, <ic2:resource:13>, <minecraft:end_rod>], [<ic2:plate:7>, <ic2:plate:7>, <ic2:plate:7>]]);
recipes.remove(<xnet:router>);
recipes.addShaped(<xnet:router>, [[<immersiveengineering:wooden_device0:3>, <techreborn:plates:16>, <immersiveengineering:wooden_device0:7>],[<techreborn:plates:16>, <ic2:resource:13>, <techreborn:plates:16>], [<ic2:plate:7>, <ic2:plate:7>, <ic2:plate:7>]]);
recipes.remove(<xnet:controller>);
recipes.addShaped(<xnet:controller>, [[<techreborn:plates:16>, <ic2:plate:7>, <techreborn:plates:16>],[<ic2:plate:7>, <ic2:resource:13>, <ic2:plate:7>], [<techreborn:plates:16>, <ic2:plate:7>, <techreborn:plates:16>]]);